GradProjectV5/Models/Consult.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GradProjectV5.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Consult
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Consult()
    {

        this.ConsultAnswers = new HashSet<ConsultAnswer>();

    }


    public int ID { get; set; }

    public string ConsultQuestionTitle { get; set; }

    public string ConsultQuestionName { get; set; }

    public string AvailableFilePath { get; set; }

    public Nullable<int> QuestionerId { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> QuestionDate { get; set; }

    public Nullable<int> ConsultTypeId { get; set; }



    public virtual Member Member { get; set; }

    public virtual ConsultType ConsultType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConsultAnswer> ConsultAnswers { get; set; }

}

}

GradProjectV5/Models/ConsultType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GradProjectV5.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ConsultType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ConsultType()
    {

        this.Consults = new HashSet<Consult>();

    }


    public int ID { get; set; }

    public string ConsultTypeName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Consult> Consults { get; set; }

}

}

GradProjectV5/Controllers/ConsultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GradProjectV5.Models;
using Microsoft.AspNet.Identity;

namespace GradProjectV5.Controllers
{
    [Authorize]
    [SessionState(System.Web.SessionState.SessionStateBehavior.Required)]
    public class ConsultController : Controller
    {
        [HttpGet]
        public ActionResult AddConsultType()
        {
            return View();
        }


        [HttpPost]
        public ActionResult AddConsultType(ConsultType c)
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            ConsultType consultType = new ConsultType();
            consultType.ConsultTypeName = c.ConsultTypeName;
            db.ConsultTypes.Add(consultType);
            db.SaveChanges();
            return RedirectToAction("Create");
        }


        
        [HttpGet]
        public dynamic LoadConsultType()
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            var tmp = db.ConsultTypes.Select(x => new
            {
                x.ID,
                x.ConsultTypeName
            }).ToList();
            return Json(tmp , JsonRequestBehavior.AllowGet) ;
        }
        // GET: DoctorQuestions
        [HttpGet]
        public dynamic Index()
        {
            return View();
        }


        [HttpGet]
        public dynamic LoadQuestionsView()
        {
            return View();
        }

        [HttpGet]
        public dynamic LoadQuestionsForAnswer()
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            var userid = User.Identity.GetUserId();
            var member = db.Members.FirstOrDefault(x => x.UserId == userid);
            var tmp = db.Consults.Where(x => x.IsDeleted == false && x.ConsultAnswers.FirstOrDefault(c =>c.AnsweredById ==member.ID)== null).Select(x => new
            {
                x.ID,
                AvailableFilePath = x.AvailableFilePath == null ? "" : x.AvailableFilePath,
                ConsultQuestionTitle = x.ConsultQuestionTitle == null ? "" : x.ConsultQuestionTitle,
                ConsultQuestionName = x.ConsultQuestionName == null ? "" : x.ConsultQuestionName,
                ConsultTypeName = x.ConsultTypeId == null ? "" : x.ConsultType.ConsultTypeName,
                QuestionerName= x.QuestionerId == null ?"":x.Member.FullName,
                Age = x.QuestionerId == null ?"": x.Member.Age,
                GenderName = x.QuestionerId == null ?"": x.Member.Gender.GenderName,

                Qday = x.QuestionDate == null ?0: x.QuestionDate.Value.Day,
                Qmonth = x.QuestionDate == null ?0: x.QuestionDate.Value.Month,
                Qyear = x.QuestionDate == null ?0: x.QuestionDate.Value.Year
               

            }).ToList();

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public dynamic LoadQuestionsWithAnswers()
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            var tmp = db.Consults.Where(x => x.IsDeleted == false).Select(x => new
            {

                AvailableFilePath = x.AvailableFilePath == null ? "" : x.AvailableFilePath,
                ConsultQuestionTitle = x.ConsultQuestionTitle == null ? "" : x.ConsultQuestionTitle,
                ConsultQuestionName = x.ConsultQuestionName == null ? "" : x.ConsultQuestionName,
                ConsultTypeName = x.ConsultTypeId == null ? "" : x.ConsultType.ConsultTypeName,
                QuestionerName= x.QuestionerId == null ?"":x.Member.FullName,
                Age = x.QuestionerId == null ?"": x.Member.Age,
                GenderName = x.QuestionerId == null ?"": x.Member.Gender.GenderName,

                Qday = x.QuestionDate == null ?0: x.QuestionDate.Value.Day,
                Qmonth = x.QuestionDate == null ?0: x.QuestionDate.Value.Month,
                Qyear = x.QuestionDate == null ?0: x.QuestionDate.Value.Year,
                ConsultAnswersResult =x.ConsultAnswers.Where(q =>q.IsDeleted == false && q.ConsultId == x.ID).Select(q =>new
                {
                    ResponderName= x.QuestionerId == null ?"":q.Member.FullName,
                    Rday = q.AnswerDate == null ?0: q.AnswerDate.Value.Day,
                    Rmonth = q.AnswerDate == null ?0: q.AnswerDate.Value.Month,
                    Ryear = q.AnswerDate == null ?0: q.AnswerDate.Value.Year,
                    Answer=q.Answer == null ?"":q.Answer
                })


            }).ToList();

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }


        // GET: DoctorQuestions
        public ActionResult Create()
        {
            return View();
        }


       [HttpPost]
        public ActionResult Create(Consult c)
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            Consult consult = new Consult();
            var userid = User.Identity.GetUserId();
            var member = db.Members.FirstOrDefault(x => x.UserId == userid);
            if (member != null)
                consult.QuestionerId = member.ID;
            if (Session["ConsultFile"] != null)
            {
                List<string>consultfileList = (List<string>) Session["ConsultFile"];
                consult.AvailableFilePath = consultfileList[0];
                Session.Remove("ConsultFile");

            }

            consult.ConsultQuestionName = c.ConsultQuestionName;
            consult.ConsultQuestionTitle = c.ConsultQuestionTitle;
            consult.ConsultTypeId = c.ConsultTypeId;
            consult.IsDeleted = false;
            consult.QuestionDate = DateTime.Now;
            db.Consults.Add(consult);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpPost]
        public dynamic SaveConsultAnswer(int consultid, string answer)
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            var userid = User.Identity.GetUserId();
            var member = db.Members.FirstOrDefault(x => x.UserId == userid);
            ConsultAnswer consultAnswer = new ConsultAnswer();
            consultAnswer.AnswerDate = DateTime.Now;
            consultAnswer.IsDeleted = false;
            consultAnswer.Answer = answer;
            consultAnswer.ConsultId = consultid;
            if (member != null)
                consultAnswer.AnsweredById = member.ID;
            db.ConsultAnswers.Add(consultAnswer);
            db.SaveChanges();
            return "تم تسجيل ردك بنجاح";
        }

        #region consult_files





        [HttpPost]
        public void addFiles(dynamic file_name, dynamic respons)
        {



            string File_Name = respons.ToString();
            ;


            List<string> DicFile = new List<string>();
            if (Session["ConsultFile"] != null)
            {

                DicFile = (List<string>)Session["ConsultFile"];
                if (DicFile.Any(a => a == File_Name))
                    DicFile.Remove(File_Name);
            }

            DicFile.Add(File_Name);
            Session.Add("ConsultFile", DicFile);

        }



        [HttpPost]
        public void Remove_This_FileName(dynamic filename)
        {
            string canceledFile = filename.ToString();
            List<string> AllFiles = (List<string>)Session["ConsultFile"];
            if (AllFiles != null)
            {
                for (int i = 0; i < AllFiles.Count; i++)
                {


                    if (AllFiles[i].Contains(canceledFile))
                    {
                        AllFiles.Remove(AllFiles[i]);
                    }

                }


                Session["ConsultFile"] = AllFiles;



            }

        }
  

        #endregion

    }

}

GradProjectV5/Views/Consult/AddConsultType.cshtml
@model GradProjectV5.Models.ConsultType

@{
    ViewBag.Title = "AddConsultType";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddConsultType</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ConsultType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ConsultTypeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConsultTypeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConsultTypeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    
} 

GradProjectV5/Views/Consult/Create.cshtml
@model GradProjectV5.Models.Consult

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

      <div class="form-group">
        <div class="col-sm-2">
            <label class="control-label py-2">نوع الإستشارة  </label>
        </div>
        <div class="col-sm-10">
            <select id="ConsultTypeId" name="ConsultTypeId" class="form-control p-2"></select>
            @Html.ValidationMessageFor(model => model.ConsultTypeId, "", new { @class = "text-danger" })

        </div>
        <div class="col-sm-1">
            <a href="@Url.Action("AddConsultType")"><i class="fa fa-plus" style="color:blue;font-weight:bold"></i></a>

        </div>
    </div>

    <div class="form-group py-2">
        <div class="col-sm-2">
            @Html.LabelFor(model => model.ConsultQuestionTitle, htmlAttributes: new { @class = "control-label py-2 " })
        </div>
        <div class="col-sm-10">
            @Html.EditorFor(model => model.ConsultQuestionTitle, new { htmlAttributes = new { @class = "form-control p-2" , placeholder = "ادخل عنوان الإستشارة " } })
            @Html.ValidationMessageFor(model => model.ConsultQuestionTitle, "", new { @class = "text-danger" })
        </div>
        <div class="col-sm-1"></div>

    </div>
    <div class="form-group py-2">
        <div class="col-sm-2">
            @Html.LabelFor(model => model.ConsultQuestionName, htmlAttributes: new { @class = "control-label py-2 " })
        </div>
        <div class="col-sm-10">
            @*@Html.TextAreaFor(model => model.ConsultQuestionName, new { htmlAttributes = new { @class = "form-control p-2" } })*@
            @*<textarea name="ConsultQuestionName" class="form-control" placeholder="ادخل الإستشارة بالتفاصيل "></textarea>*@
            @Html.EditorFor(c=>c.ConsultQuestionName,new { htmlAttributes=new {placeholder="ادخل الإستشارة بالتفاصيل", @class = "form-control" } })

            @Html.ValidationMessageFor(model => model.ConsultQuestionName, "", new { @class = "text-danger" })
        </div>
        <div class="col-sm-1"></div>

    </div>
    




    <div class="form-group mt-3">
        <div class="col-sm-2">
            <label class="control-label p-2">
               (إختياري) إرفاق ملف
            </label>
        </div>
        <div class="col-sm-10 mt-2">
            <div class="dropzone  dropzone-previews class1" id="myawesomedropzone"></div>

        </div>

    </div>


    <div class="form-group pt-4 w-100 text-center py-4 ">
        <div class="col-sm-10 ">
            <input type="submit" id="btnSaveds" value="حفظ" class="btn btn-primary w-100 py-2" />

        </div>
    </div>


}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(document).ready(function() {


            window.Dropzone.options.myawesomedropzone = {
                url: '../Upload.ashx',
                addRemoveLinks: true,
                

                removedfile: function (file) {
                    RemoveThisFileName(file.name);


                    file.previewElement.remove();


                },

                success: function (file, response) {
                    var url = "@Url.Action("addFiles", "Consult")";
                    CreateAjaxRequest(url,"post", { file_name: file.name, respons: response });
                    file.previewElement.classList.add("dz-success");
                },
                previewsContainer: ".class1",
                uploadMultiple: false,
                parallelUploads: 100,
                maxFiles: 1,
                init: function () {
                    var myAwesomeDropzone = this;
                    $("#btnSaveds").click(function () {
                        myAwesomeDropzone.removeAllFiles(true);
                    });
                }
            }


            LoadConsultTypes();
           // LoadMedicine();
          //  LoadPhMedicineRequest();
        });



        function RemoveThisFileName(name) {
            var url = "@Url.Action("Remove_This_FileName", "Consult")";

             CreateAjaxRequest(url,"post", { filename: name });
        }


        function LoadConsultTypes() {
            $('#ConsultTypeId option').each(function() {
                $(this).remove();
            });
            var url = "@Url.Action("LoadConsultType", "Consult")";
            var result = CreateAjaxRequest(url, "get", {});
            for (var i in result) {
                $("#ConsultTypeId").append('<option value=' + result[i].ID + '>' + result[i].ConsultTypeName + '</option>');
            }


        }

        function LoadMedicine() {
            $('#MedicineId option').each(function() {
                $(this).remove();
            });
            var url = "@Url.Action("Index", "Medicine")";
            var result = CreateAjaxRequest(url, "get", {});
            for (var i in result) {
                $("#MedicineId").append('<option value=' + result[i].ID + '>' + result[i].MedicineName + '</option>');
            }


        }

        function LoadPhMedicineRequest() {
            var url = "@Url.Action("GetPhRequestedMedicine", "Pharmacy")";

            $("#PharmacyRequestMedicineDiv").html('');
            var tr = '';
            var result = CreateAjaxRequest(url, "get", {});

            if (result != null) {
                if (result.length > 0) {


                    tr += '<table class="table table-striped table-bordered table-hover dataTables-example">';
                    tr += '<thead>';
                    tr += '   <tr>';
                    tr += '       <th>إسم الصيدلية</th>';
                    tr += '       <th> الدواء المطلوب</th>';
                    tr += '       <th> الكمية</th>';
                    tr += '       <th>تاريخ الطلب</th>';
                    tr += '       <th>حالة الطلب</th>';
                    tr += '       <th>الجهة التي ردت علي الطلب</th>';
                    tr += '       <th>تاريخ الرد</th>';
                    tr += '       <th>إنهاء الطلب</th>';

                    tr += '    </tr>';
                    tr += '</tr></thead>';
                    tr += '<tbody>';


                    for (var i = 0; i < result.length; i++) {
                        tr += '<tr>';
                        tr += '<td>' + result[i].RequestPharmacy + '</td>';
                        tr += '<td>' + result[i].MedicineName + '</td>';
                        tr += '<td>' + result[i].RequestedAmount + '</td>';
                        tr += '<td>' + result[i].requestday + "/" + result[i].requestmonth+ "/" + result[i].requestyear + '</td>';
                        tr += '<td>' + result[i].StatusName + '</td>';
                        tr += '<td>' + result[i].RespondPharmacy + '</td>';
                        if (result[i].respondyear == 0) {
                            tr += '<td></td>';
                        } else {
                            tr += '<td>' + result[i].respondday + "/" + result[i].respondmonth + "/" + result[i].respondyear + '</td>';

                        }

                        tr += '<td><button type="button"onclick="CloseMedicineRequest(' + result[i].ID+');" class="btn btn-primary ">إغلاق</button></td>';

                        tr += '</tr>';
                    }

                    tr += '</tbody>';
                    tr += '  </table>';
                    tr += '<br>';
                    tr +=
                        '<p>يمكنك إضافة الدواء الفائض عن احتياجك عن طريق الضغط علي <a href="#" onclick="EditThisMember();return false;"><i class="fa fa-plus" style="color:blue;font-weight:bold"></i></a>';
                    tr +=
                        '<p>يمكنك طلب الدواء الناقص لديك عن طريق الضغط علي <a href="@Url.Action("") "><i class="fa fa-plus" style="color:blue;font-weight:bold"></i></a>';
                    $("#GetAllMembersDiv").append(tr);
                    $('.dataTables-example').DataTable({
                        "ordering": false
                    });
                }
            }
            $("#PharmacyRequestMedicineDiv").append(tr);
        }


        function CloseMedicineRequest(id) {
            var x = confirm("هل انت متأكد من تنفيذ هذا الإجراء");
            if (x == true) {
                var url = "@Url.Action("CloseMedicineRequest","Pharmacy")";
                var result = CreateAjaxRequest(url,
                    "post",
                    {
                        requestid: id
                    });
                alert(result);
                LoadPhMedicineRequest();
            }
        }
    </script>
}







  

GradProjectV5/Views/Consult/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="AllQuestionsWithAnswersDiv">'</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            LoadAllQuestionsAnswers();
        });


        function LoadAllQuestionsAnswers() {
            $("#AllQuestionsWithAnswersDiv").html("");
            var comp = '';
            var url = "@Url.Action("LoadQuestionsWithAnswers","Consult")";
            var result = CreateAjaxRequest(url, "get", {});
            for (var i in result) {
                comp += '<div class="container p-2" style="border: 2px solid aliceblue">';
                comp += '<div class="row" id="ConsultDiv">';
                comp += '<div class="col-sm-12">';
                comp += '<div class="clearfix py-3 px-2">';
                comp += '<div class="float-start text-black-50">' + result[i].GenderName + " , " + result[i].Age +'</div>';
                comp += '<div class="float-end " style="background: #fff7e9; color: #ffad1f;border-radius: 5px">' + result[i].ConsultTypeName+'</div>';
                comp +=
                    ' <p class="py-3 lead px-2" style="font-weight: 400;line-height: 1.56;color: #454551;">' + result[i].ConsultQuestionName+'؟</p>';
                for (var j in result[i].ConsultAnswersResult) {
                    comp += ' <hr />';
              



                    comp += '<div class="row">';
                    comp += '<span class="col-sm-1">';
                    comp += '<img class="rounded imgdoctor" src="../Content/Images/Doctorlogo.jpg" />';
                    comp += '</span>';


                    comp += '<div class="col-sm-11 m-sm-3 m-md-0" style="font-weight: 500;line-height: 1.36">';
                    comp +=
                        '<div style=" color: #18a8aa;" >الدكتور ' + result[i].ConsultAnswersResult[j].ResponderName+' اجاب علي السؤال ';
                    comp += '</div>';
                    comp += '<div class="text-black-50 py-1">'+result[i].ConsultAnswersResult[j].Rday+"/" + result[i].ConsultAnswersResult[j].Rmonth + "/" + result[i].ConsultAnswersResult[j].Ryear+'</div>';
                    comp += ' <p class="py-3 lead px-2" style="font-weight: 400;line-height: 1.56;color: #454551;">' + result[i].ConsultAnswersResult[j].Answer+'</p>';

                    comp += '</div>';
                    comp += '</div>';


                }
                comp += '</div>';
                comp += '</div>';
                comp += '</div>';
                comp += ' </div >';

            }
            comp += '<br/><br/>';
            $("#AllQuestionsWithAnswersDiv").append(comp);

        }
    </script>
}

GradProjectV5/Views/Consult/LoadQuestionsView.cshtml
@{
    ViewBag.Title = "LoadQuestionsView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="ConsultQuestionsDiv"></div>


<div class="modal fade" id="AnswerQuestionModel" tabindex="-1" aria-labelledby="OpenAnswerQuestionModelModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-body">
                <div class="form-group">
                    <div class="col-md-12">
                        <label class="control-label py-2">الرد</label>
                    </div>
                    <div class="col-md-12">
                        <textarea id="txt_answer" class="form-control p-2"></textarea>
                    </div>

                </div>
                <div class="modal-footer">

                    <button type="button" onclick="SaveQuestionAnswer();" class="btn btn-primary ">حفظ</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إغلاق</button>
      
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(document).ready(function() {
            LoadQuestionsToAnswer();
        });


        function LoadQuestionsToAnswer() {
            var url = "@Url.Action("LoadQuestionsForAnswer", "Consult")";

            $("#ConsultQuestionsDiv").html('');
            var tr = '';
            var result = CreateAjaxRequest(url, "get", {});

            if (result != null) {
                if (result.length > 0) {


                    tr += '<table class="table table-striped table-bordered table-hover dataTables-example">';
                    tr += '<thead>';
                    tr += '   <tr>';
                    tr += '       <th>مقدم السؤال</th>';
                    tr += '       <th>تاريخ تقديم السؤال</th>';
                    tr += '       <th> الجنس</th>';
                    tr += '       <th> السن</th>';
                    tr += '       <th> نوع السؤال</th>';
                    tr += '       <th>عنوان السؤال</th>';
                    tr += '       <th>السؤال</th>';
                    tr += '       <th>الصورة المتاحة</th>';
                    tr += '       <th>إضافة رد</th>';

                    tr += '</tr>';
                    tr += '</thead>';
                    tr += '<tbody>';


                    for (var i = 0; i < result.length; i++) {
                        tr += '<tr>';
                        tr += '<td>' + result[i].QuestionerName + '</td>';
                        if (result[i].Qyear == 0) {
                            tr += '<td></td>';
                        } else {
                            tr += '<td>' + result[i].Qday + "/" + result[i].Qmonth + "/" + result[i].Qyear + "</td>";
                        }
                        tr += '<td>' + result[i].GenderName + '</td>';
                        tr += '<td>' + result[i].Age + '</td>';
                        tr += '<td>' + result[i].ConsultTypeName + "</td>";
                        tr += '<td>' + result[i].ConsultQuestionTitle + '</td>';
                        tr += '<td>' + result[i].ConsultQuestionName + '</td>';
                        if (result[i].AvailableFilePath == "") {
                            tr += '<td></td>';
                        } else {
                            tr += '<td><a target="_blank" href="../uploads/' + result[i].AvailableFilePath + '">Preview</a></td>';
                        }

                        tr += '<td><button type="button"onclick="OpenAnswerQuestionModel(' + result[i].ID + ');" class="btn btn-primary ">رد</button></td>';
                        tr += '</tr>';
                    }

                    tr += '</tbody>';
                    tr += '  </table>';
                    $("#GetAllMembersDiv").append(tr);
                    $('.dataTables-example').DataTable({
                        "ordering": false
                    });
                }
            }
            $("#ConsultQuestionsDiv").append(tr);
        }



        function OpenAnswerQuestionModel(id) {

            global_consult_id = id;
            $('#AnswerQuestionModel').modal('show');

        }


        function SaveQuestionAnswer() {
            var answer = $("#txt_answer").val();
            if (answer == "") {
                alert("من فضلك أدخل إجابة");
            } else {
                var url = "@Url.Action("SaveConsultAnswer","Consult")";
                var result = CreateAjaxRequest(url,
                    "post",
                    {
                        consultid: global_consult_id,
                        answer: answer
                    });
                alert(result);
                $("#txt_answer").val(null);
                LoadQuestionsToAnswer();

            }
        }
    </script>
}