GradProjectV5/Controllers/DonateMedicineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GradProjectV5.Models;
using Microsoft.AspNet.Identity;

namespace GradProjectV5.Controllers
{
    [Authorize]
    public class DonateMedicineController : Controller
    {
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public dynamic Create(BeneficierMedicineRequest b)
        {
            if (ModelState.IsValid)
            {
                MyProjectDBEntities db = new MyProjectDBEntities();
                var userid = User.Identity.GetUserId();
                var member = db.Members.FirstOrDefault(x => x.UserId == userid);
                BeneficierMedicineRequest beneficierMedicineRequest = new BeneficierMedicineRequest();
                beneficierMedicineRequest.RequestedAmount = b.RequestedAmount;
                beneficierMedicineRequest.LatestStatusId = 1;
                beneficierMedicineRequest.IsDeleted = false;
                beneficierMedicineRequest.BeneficierId = member.ID;
                beneficierMedicineRequest.MedicineId = b.MedicineId;
                beneficierMedicineRequest.RequestDate = DateTime.Now;
                db.BeneficierMedicineRequests.Add(beneficierMedicineRequest);
                db.SaveChanges();
                BMedicineRequestStatu bMedicineRequestStatu = new BMedicineRequestStatu();
                bMedicineRequestStatu.BRequestId = beneficierMedicineRequest.ID;
                bMedicineRequestStatu.StatusId = 1;
                bMedicineRequestStatu.Date = DateTime.Now;
                db.BMedicineRequestStatus.Add(bMedicineRequestStatu);
                db.SaveChanges();
                return true;


            }


            return View(b);
        }


        [HttpGet]
        public dynamic LoadRequestsToDonate()
        {
            return View();
        }



        
        [HttpPost]
        public dynamic LoadRequestsDataToDonate()
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            var userid = User.Identity.GetUserId();
            var member = db.Members.FirstOrDefault(x => x.UserId == userid);
            var tmp = db.BeneficierMedicineRequests.Where(x => x.IsDeleted == false && 
                                                               x.DonatorId != member.ID).Select(x => new
            {
                x.ID,
                BenificierFullName= x.BeneficierId == null ?"":x.Member1.FullName,
                MedicineName = x.MedicineId == null ?"": x.Medicine.MedicineName,
                Rday = x.RequestDate == null ?0: x.RequestDate.Value.Day,
                Rmonth = x.RequestDate == null ?0: x.RequestDate.Value.Month,
                Ryear = x.RequestDate == null ?0: x.RequestDate.Value.Year,
                StatusName = x.LatestStatusId == null ?"": x.Status.StatusName,
                RequestedAmount = x.RequestedAmount == null ?"": x.RequestedAmount,
               

            }).ToList();

            return Json(tmp, JsonRequestBehavior.AllowGet);

        }



        [HttpPost]
        public dynamic DonateMedicine(string amount , int requestid)
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            var userid = User.Identity.GetUserId();
            var member = db.Members.FirstOrDefault(x => x.UserId == userid);
            var tmp = db.BeneficierMedicineRequests.Find(requestid);
            tmp.RespondDate = DateTime.Now;
            tmp.RespondedAmount = amount;
            tmp.DonatorId = member.ID;
            tmp.LatestStatusId = 2;
            db.SaveChanges();
            BMedicineRequestStatu bMedicineRequestStatu = new BMedicineRequestStatu();
            bMedicineRequestStatu.Date = DateTime.Now;
            bMedicineRequestStatu.StatusId = 2;
            bMedicineRequestStatu.BRequestId = requestid;
            db.BMedicineRequestStatus.Add(bMedicineRequestStatu);
            db.SaveChanges();

            return "تم التبرع بنجاح";
        }


        [HttpGet]
        public dynamic Index()
        {
            return View();
        }


        
        [HttpPost]
        public dynamic LoadDonatedRequests()
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            var tmp = db.BeneficierMedicineRequests.Where(x => x.IsDeleted == false).Select(x => new
            {
                BenificierFullName= x.BeneficierId == null ?"":x.Member1.FullName,
                x.BeneficierId,
                x.DonatorId,
                DonatorFullName= x.DonatorId == null ?"":x.Member.FullName,
                MedicineName = x.MedicineId == null ?"": x.Medicine.MedicineName,
                Rday = x.RequestDate == null ?0: x.RequestDate.Value.Day,
                Rmonth = x.RequestDate == null ?0: x.RequestDate.Value.Month,
                Ryear = x.RequestDate == null ?0: x.RequestDate.Value.Year,  
                Respondday = x.RespondDate == null ?0: x.RespondDate.Value.Day,
                Respondmonth = x.RespondDate == null ?0: x.RespondDate.Value.Month,
                Respondyear = x.RespondDate == null ?0: x.RespondDate.Value.Year,
                StatusName = x.LatestStatusId == null ?"": x.Status.StatusName,
                RequestedAmount = x.RequestedAmount == null ?"": x.RequestedAmount,
                RespondedAmount = x.RespondedAmount == null ?"": x.RespondedAmount,

            }).ToList();
            return Json(tmp, JsonRequestBehavior.AllowGet);
        }
    }



}

GradProjectV5/Views/DonateMedicine/Create.cshtml
@model GradProjectV5.Models.BeneficierMedicineRequest

@{
    ViewBag.Title = "RequestMedicine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        <div class="col-sm-2">
            <label class="control-label py-2">اسم الدواء </label>

        </div>
        <div class="col-sm-10">
            <select id="MedicineId" name="MedicineId" class="form-control p-2"></select>
        </div>
        <div class="col-sm-1">
            @*<a href="@Url.Action("Create","Medicine" )"><i class="fa fa-plus" style="color:blue;font-weight:bold"></i></a>*@

        </div>
    </div>



    <div class="form-group">
        <div class="col-sm-2">
            @Html.LabelFor(model => model.RequestedAmount, htmlAttributes: new { @class = "control-label py-2 " })
        </div>
        <div class="col-sm-10">
            @Html.EditorFor(model => model.RequestedAmount, new { htmlAttributes = new { @class = "form-control p-2" } })
            @Html.ValidationMessageFor(model => model.RequestedAmount, "", new { @class = "text-danger" })
        </div>
        <div class="col-sm-1"></div>

    </div>











    <div class="form-group pt-4 w-100 text-center py-4 ">
        <div class="col-sm-10 ">
            <input type="submit" value="حفظ" class="btn btn-primary w-100 py-2" />

        </div>
    </div>


    <br />
    <br />
    <div id="PharmacyRequestMedicineDiv"></div>

}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(document).ready(function() {
            LoadMyPharmacies();
            LoadMedicine();
            LoadPhMedicineRequest();
        });


        function LoadMyPharmacies() {
            $('#RequestPharamcyId option').each(function() {
                $(this).remove();
            });
            var url = "@Url.Action("GetMyPharmacies", "Pharmacy")";
            var result = CreateAjaxRequest(url, "post", {});
            for (var i in result) {
                $("#RequestPharamcyId")
                    .append('<option value=' + result[i].ID + '>' + result[i].PharmacyName + '</option>');
            }


        }

        function LoadMedicine() {
            $('#MedicineId option').each(function() {
                $(this).remove();
            });
            var url = "@Url.Action("Index", "Medicine")";
            var result = CreateAjaxRequest(url, "get", {});
            for (var i in result) {
                $("#MedicineId").append('<option value=' + result[i].ID + '>' + result[i].MedicineName + '</option>');
            }


        }

        function LoadPhMedicineRequest() {
            var url = "@Url.Action("GetPhRequestedMedicine", "Pharmacy")";

            $("#PharmacyRequestMedicineDiv").html('');
            var tr = '';
            var result = CreateAjaxRequest(url, "get", {});

            if (result != null) {
                if (result.length > 0) {


                    tr += '<table class="table table-striped table-bordered table-hover dataTables-example">';
                    tr += '<thead>';
                    tr += '   <tr>';
                    tr += '       <th>إسم الصيدلية</th>';
                    tr += '       <th> الدواء المطلوب</th>';
                    tr += '       <th> الكمية</th>';
                    tr += '       <th>تاريخ الطلب</th>';
                    tr += '       <th>حالة الطلب</th>';
                    tr += '       <th>الجهة التي ردت علي الطلب</th>';
                    tr += '       <th>تاريخ الرد</th>';
                    tr += '       <th>إنهاء الطلب</th>';

                    tr += '    </tr>';
                    tr += '</tr></thead>';
                    tr += '<tbody>';


                    for (var i = 0; i < result.length; i++) {
                        tr += '<tr>';
                        tr += '<td>' + result[i].RequestPharmacy + '</td>';
                        tr += '<td>' + result[i].MedicineName + '</td>';
                        tr += '<td>' + result[i].RequestedAmount + '</td>';
                        tr += '<td>' + result[i].requestday + "/" + result[i].requestmonth+ "/" + result[i].requestyear + '</td>';
                        tr += '<td>' + result[i].StatusName + '</td>';
                        tr += '<td>' + result[i].RespondPharmacy + '</td>';
                        if (result[i].respondyear == 0) {
                            tr += '<td></td>';
                        } else {
                            tr += '<td>' + result[i].respondday + "/" + result[i].respondmonth + "/" + result[i].respondyear + '</td>';

                        }

                        tr += '<td><button type="button"onclick="CloseMedicineRequest(' + result[i].ID+');" class="btn btn-primary ">إغلاق</button></td>';

                        tr += '</tr>';
                    }

                    tr += '</tbody>';
                    tr += '  </table>';
                  
                    $("#GetAllMembersDiv").append(tr);
                    $('.dataTables-example').DataTable({
                        "ordering": false
                    });
                }
            }
            $("#PharmacyRequestMedicineDiv").append(tr);
        }


        function CloseMedicineRequest(id) {
            var x = confirm("هل انت متأكد من تنفيذ هذا الإجراء");
            if (x == true) {
                var url = "@Url.Action("CloseMedicineRequest","Pharmacy")";
                var result = CreateAjaxRequest(url,
                    "post",
                    {
                        requestid: id
                    });
                alert(result);
                LoadPhMedicineRequest();
            }
        }
    </script>
}

GradProjectV5/Views/DonateMedicine/Index.cshtml
<div class="modal fade" id="MemberDetailsModal" tabindex="-1" aria-labelledby="OpenDonateMedicineModalModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            </div>
            <div class="modal-body" id="MemberDetailsModalBody">
              


                </div>
         

            </div>
            <div class="modal-footer">
            

            </div>
        </div>
    </div>


<div id="DonatedRequestsDiv">

</div>
@section scripts
{
    <script>
        $(document).ready(function() {
            LoadDonatedRequests();
        });


                    function LoadDonatedRequests() {
                var url = "@Url.Action("LoadDonatedRequests", "DonateMedicine")";

                $("#DonatedRequestsDiv").html('');
                var tr = '';
                var result = CreateAjaxRequest(url, "post", {});

                if (result != null) {
                    if (result.length > 0) {


                        tr += '<table class="table table-striped table-bordered table-hover dataTables-example">';
                        tr += '<thead>';
                        tr += '   <tr>';
                        tr += '       <th>مقدم الطلب</th>';
                        tr += '       <th>الدواء المطلوب</th>';
                        tr += '       <th>تاريخ التقديم</th>';
                        tr += '       <th> الكمية المطلوبة</th>';
                        tr += '       <th>المتبرع </th>';
                        tr += '       <th>الكمية المتاحة </th>';
                        tr += '       <th>تاريخ الرد </th>';
                        tr += '       <th>الحالة النهائية </th>';

                        tr += '    </tr>';
                        tr += '</tr></thead>';
                        tr += '<tbody>';


                        for (var i = 0; i < result.length; i++) {
                            tr += '<tr>';
                            tr += '<td><a href="#" onclick="GetMemberDetails(' + result[i].BeneficierId+');return false;">' + result[i].BenificierFullName + '</a></td>';
                            tr += '<td>' + result[i].MedicineName + '</td>';
                            tr += '<td>' + result[i].Rday + "/"+result[i].Rmonth + "/"+result[i].Ryear + '</td>';
                            tr += '<td>' + result[i].RequestedAmount + '</td>';
                            tr += '<td><a href="#" onclick="GetMemberDetails(' + result[i].DonatorId + ');return false;">' + result[i].DonatorFullName + '</a></td>';

                            tr += '<td>' + result[i].RespondedAmount + '</td>';
                            if (result[i].Respondyear == 0) {
                                tr += '<td></td>';
                            } else {
                                tr += '<td>' + result[i].Respondday + "/" + result[i].Respondmonth + "/" + result[i].Respondyear + '</td>';

                            }
                            tr += '<td>' + result[i].StatusName + '</td>';
                            tr += '</tr>';
                        }

                        tr += '</tbody>';
                        tr += '  </table>';
                        tr += '<br>';
                        $("#GetAllMembersDiv").append(tr);
                        $('.dataTables-example').DataTable({
                            "ordering": false
                        });
                    }
                }
                $("#DonatedRequestsDiv").append(tr);
                    }


        function GetMemberDetails(ID) {
            $("#MemberDetailsModalBody").html("");
            var url = "@Url.Action("LoadMemberDetails","MEMBER")";
            var result = CreateAjaxRequest(url, "post", { memberid: ID });
            var tr = '';
            tr += '<table style="width:100%" class="table table-bordered  table-striped  "> ';
            tr += '<tbody>';
            for (var i in result) {

                tr += '<tr >';
                tr += ' <td>الإسم</td>';
                tr += ' <td  >' + result[i].FullName + '</td>';
                tr += '</tr>';
                tr += '<tr >';
                tr += ' <td>رقم الهاتف</td>';
                tr += ' <td  >' + result[i].PhoneNo + '</td>';
                tr += '</tr>';
                tr += '<tr >';
                tr += ' <td>العنوان</td>';
                tr += ' <td  >' + result[i].Address + '</td>';
                tr += '</tr>';
                tr += '<tr >';
                tr += ' <td>المحافظة</td>';
                tr += ' <td  >' + result[i].GovernarteName + '</td>';
                tr += '</tr>';
                tr += '<tr >';
                tr += ' <td>المدينة</td>';
                tr += ' <td  >' + result[i].CityName + '</td>';
                tr += '</tr>';
           
          
         
           
            





      

            }

            tr += '</tbody>';
            tr += '  </table>';
            $("#MemberDetailsModalBody").append(tr);
            $("#MemberDetailsModal").modal('show');

        }




    </script>
}

GradProjectV5/Views/DonateMedicine/LoadRequestsToDonate.cshtml
@{
    ViewBag.Title = "LoadRequestsToDonate";
}

<div id="MedicineRequestDiv"></div>


<div class="modal fade" id="AnswerQuestionModel" tabindex="-1" aria-labelledby="OpenDonateMedicineModalModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-body">
                <div class="form-group">
                    <div class="col-md-12">
                        <label class="control-label py-2">الكمية المتاحة</label>
                    </div>
                    <div class="col-md-12">
                        <input type="number" id="txt_availableamount" class="form-control p-2"/>
                    </div>

                </div>
                <div class="modal-footer">

                    <button type="button" onclick="DonateMedicine();" class="btn btn-primary ">حفظ</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إغلاق</button>
      
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(document).ready(function() {
            LoadRequestToAnswer();
        });


        function LoadRequestToAnswer() {
            var url = "@Url.Action("LoadRequestsDataToDonate", "DonateMedicine")";

            $("#MedicineRequestDiv").html('');
            var tr = '';
            var result = CreateAjaxRequest(url, "post", {});

            if (result != null) {
                if (result.length > 0) {


                    tr += '<table class="table table-striped table-bordered table-hover dataTables-example">';
                    tr += '<thead>';
                    tr += '   <tr>';
                    tr += '       <th>مقدم الطلب</th>';
                    tr += '       <th>تاريخ تقديم الطلب</th>';
                    tr += '       <th> الدواء الناقص </th>';
                    tr += '       <th> الكمية المطلوبة</th>';
                    tr += '       <th> حالة الطلب</th>';
                    tr += '       <th>تبرع الأن</th>';

                    tr += '</tr>';
                    tr += '</thead>';
                    tr += '<tbody>';


                    for (var i = 0; i < result.length; i++) {
                        tr += '<tr>';
                        tr += '<td>' + result[i].BenificierFullName + '</td>';
                        tr += '<td>' + result[i].Rday + "/" + result[i].Rmonth + "/" + result[i].Ryear + "</td>";
                        
                        tr += '<td>' + result[i].MedicineName + '</td>';
                        tr += '<td>' + result[i].RequestedAmount + '</td>';
                        tr += '<td>' + result[i].StatusName + "</td>";
                        tr += '<td><button type="button"onclick="OpenDonateMedicineModal(' + result[i].ID + ');" class="btn btn-primary ">تبرع</button></td>';
                        tr += '</tr>';
                    }

                    tr += '</tbody>';
                    tr += '  </table>';
                    $("#GetAllMembersDiv").append(tr);
                    $('.dataTables-example').DataTable({
                        "ordering": false
                    });
                }
            }
            $("#MedicineRequestDiv").append(tr);
        }



        function OpenDonateMedicineModal(id) {

            global_rquest_id = id;
            $('#AnswerQuestionModel').modal('show');

        }


        function DonateMedicine() {

            var availableamount = $("#txt_availableamount").val();
            if (availableamount == "") {
                alert("من فضلك أدخل كمية للتبرع");
            } else {
                var url = "@Url.Action("DonateMedicine","DonateMedicine")";
                var result = CreateAjaxRequest(url,
                    "post",
                    {
                        amount: availableamount,
                        requestid: global_rquest_id
                    });
                alert(result);
                LoadRequestToAnswer();
            }


        }
    </script>
}