GradProjectV5/Models/Member.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GradProjectV5.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Member
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Member()
    {

        this.BeneficierMedicineRequests = new HashSet<BeneficierMedicineRequest>();

        this.BeneficierMedicineRequests1 = new HashSet<BeneficierMedicineRequest>();

        this.Consults = new HashSet<Consult>();

        this.ConsultAnswers = new HashSet<ConsultAnswer>();

        this.Doctors = new HashSet<Doctor>();

        this.Pharamacies = new HashSet<Pharamacy>();

    }


    public int ID { get; set; }

    public string FullName { get; set; }

    public string NationalId { get; set; }

    public string PhoneNo { get; set; }

    public Nullable<int> CityId { get; set; }

    public string Address { get; set; }

    public Nullable<int> GenderId { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string UserId { get; set; }

    public string Age { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BeneficierMedicineRequest> BeneficierMedicineRequests { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BeneficierMedicineRequest> BeneficierMedicineRequests1 { get; set; }

    public virtual City City { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Consult> Consults { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConsultAnswer> ConsultAnswers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Doctor> Doctors { get; set; }

    public virtual Gender Gender { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pharamacy> Pharamacies { get; set; }

}

}

GradProjectV5/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GradProjectV5.Models;

namespace GradProjectV5.Controllers
{
    [SessionState(System.Web.SessionState.SessionStateBehavior.Required)]
    public class MEMBERController : Controller
    {
        private MyProjectDBEntities db = new MyProjectDBEntities();

        [HttpGet]
        //[Authorize]
        public ActionResult Create()
        {
            return View();
        }





        [HttpGet]
        public ActionResult GetAllGovernrates()
        {
            var tmp = db.Governartes.Select(x => new
            {
                x.ID,
                x.GovernarteName
            }).ToList();

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult LoadGender()
        {
            var tmp = db.Genders.Where(x => x.IsDeleted == false).Select(x => new
            {
                x.ID,
                x.GenderName
            }).ToList();

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetGovCities(int governmentid)
        {
            var tmp = db.Cities.Where(x => x.GovernerateId == governmentid).Select(x => new
            {
                x.ID,
                x.CityName,
                x.Governarte.GovernarteName

            }).ToList();

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }



        // GET: /Member/Edit/5
        [HttpPost]
        public dynamic Create(
           Member m 


        )
        {


            if (ModelState.IsValid)
            {
                Member nM = new Member();
                nM.FullName = m.FullName;
                nM.GenderId = m.GenderId;
                nM.Address = m.Address;
                nM.Age = m.Age;
                nM.PhoneNo = m.PhoneNo;
                nM.CityId = m.CityId;
                nM.NationalId = m.NationalId;
                nM.IsDeleted = false;

                db.Members.Add(nM);
                db.SaveChanges();
                Session["Mid"] = nM.ID;
                return RedirectToAction("Register", "Account");
            }

            return View( m);

        }

        //// GET: /Member/Edit/5
        //[HttpPost]
        //public dynamic SaveMember(
        //    string name,
        //    string phone,
        //    string nationalid,
        //    string address,
        //    string email,
        //    int jid,
        //    int GenderId



        //    )
        //{


        //        Member m = new Member();



        //        m.FullName = name;
        //        m.GenderId = GenderId;
        //        m.Address = address;
        //        m.Email = email;
        //        m.PhoneNo = phone;
        //        m.CityId = jid;
        //        m.NationalId = nationalid;
        //        m.IsDeleted = false;
        //        if (Session["memberid"] == null)
        //    {
        //        db.Members.Add(m);
        //        db.SaveChanges();
        //        Session["Mid"] = m.ID;
        //        return true;

        //    }
        //        else
        //        {
        //            int id = Convert.ToInt32(Session["memberid"].ToString());
        //            Session.Remove("memberid");
        //            var oldvalues = db.Members.Find(id);
        //            m.ID = oldvalues.ID;
        //            db.Entry(oldvalues).CurrentValues.SetValues(m);
        //            db.SaveChanges();
        //            Session["Mid"] = m.ID;

        //            return true;
        //        }



        //}



        [HttpPost]
        public ActionResult LoadMemberDetails(int memberid)
        {
            var tmp = db.Members.Where(x => x.ID == memberid && x.IsDeleted == false).Select(x => new
            {
                x.ID,
                NationalId = x.NationalId == null ? "" : x.NationalId,
                Address = x.Address == null ? "" : x.Address,

                PhoneNo = x.PhoneNo == null ? "" : x.PhoneNo,
                FullName = x.FullName == null ? "" : x.FullName,
                CityName = x.CityId == null ? "" : x.City.CityName,
                GovernarteName = x.City.GovernerateId == null ? "" : x.City.Governarte.GovernarteName,
                GenderName = x.GenderId == null ? "" : x.Gender.GenderName,
            }).ToList();

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }



        [HttpGet]
        public ActionResult LoadMembersNoUserName()
        {
            var tmp = db.Members.Where(x => x.IsDeleted == false && x.AspNetUser == null).Select(x => new
            {
                x.ID,
                FullName = x.FullName == null ? "" : x.FullName,



            }).ToList();

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult LoadAllMembers()
        {
            var tmp = db.Members.Where(x => x.IsDeleted == false).Select(x => new
            {
                x.ID,
                NationalId = x.NationalId == null ? "" : x.NationalId,
                Address = x.Address == null ? "" : x.Address,

                PhoneNo = x.PhoneNo == null ? "" : x.PhoneNo,
                FullName = x.FullName == null ? "" : x.FullName,
                CityName = x.CityId == null ? "" : x.City.CityName,
                GovernarteName = x.City.GovernerateId == null ? "" : x.City.Governarte.GovernarteName,
                GenderName = x.GenderId == null ? "" : x.Gender.GenderName,
            }).ToList();

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult LoadMemberForEdit(int memberid)
        {
            Session["memberid"] = memberid;
            var tmp = db.Members.Where(x => x.ID == memberid).Select(x => new
            {
                x.ID,
                x.NationalId,
                GenderId = x.GenderId == null ? 0 : x.GenderId,
                Address = x.Address == null ? "" : x.Address,

                PhoneNo = x.PhoneNo == null ? "" : x.PhoneNo,
                FullName = x.FullName == null ? "" : x.FullName,
                CityID = x.CityId == null ? 0 : x.CityId,
                governmentid = x.CityId == null ? 0 : x.City.GovernerateId



            }).ToList();

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }






        [HttpPost]
        public ActionResult DeleteMember(int memberid)
        {
            var tmp = db.Members.Find(memberid);
            tmp.IsDeleted = true;
            db.SaveChanges();
            return Json("deleted successfully", JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GradProjectV5/Views/MEMBER/Create.cshtml
@model GradProjectV5.Models.Member




@{
    ViewBag.Title = "اضافة مشترك جديد";
}
<h2 class="" >الإشتراك</h2>
<div class="col-sm-10"><hr/></div>
@using (Html.BeginForm())
{

<div class="row mt-3 ">
    <div class="col-sm-12">
        <div class="col-sm-10">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <br />

                <div class="form-group">
                    <div class="col-sm-10">
                        @Html.LabelFor(model => model.FullName, new { @class = "control-label py-2" })


                    </div>
                    <div class="col-sm-10">
                       @* <input class="form-control" id="FullName" name="FullName" type="text">*@
                        @Html.EditorFor(x => x.FullName, new { htmlAttributes = new { id = "FullName" ,@class="col-sm-10 form-control"} })
                        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.PhoneNo, new { @class = "control-label py-2" })
                    </div>
                    <div class="col-sm-10">
                      @*  <input class="form-control" id="Phone" name="Phone" type="text">*@
                        @Html.EditorFor(x => x.PhoneNo, new { htmlAttributes = new { id = "Phone", @class = "col-sm-10 form-control" } })
                      @Html.ValidationMessageFor(model => model.PhoneNo ,"", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.Age, new { @class = "control-label py-2" })
                    </div>

                    <div class="col-sm-10">
                        @*<input type="number" id="txt_age"  class="form-control"/>*@
                        @Html.EditorFor(x => x.Age, new { htmlAttributes = new { id = "txt_age", @class = "col-sm-10 form-control" } })
                        @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                    </div>
                </div>

                <br />
                <div class="form-group py-2">
                    <div class="col-sm-10">
                        @Html.LabelFor(model => model.NationalId, new { @class = "control-label py-2" })


                    </div>
                    <div class="col-sm-10">
                        @*<input class="form-control" id="NationalId" name="NationalId" type="number" min="14" max="16">*@
                        @Html.EditorFor(x => x.NationalId, new { htmlAttributes = new { id = "NationalId", @class = "col-sm-10 form-control" } })
                        @Html.ValidationMessageFor(model => model.NationalId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <br />
                <div class="form-group py-2">
                    <div class="col-sm-10">
                        @Html.LabelFor(model => model.Address, new { @class = "control-label py-2" })

                    </div>
                    <div class="col-sm-10">
                        <input class="form-control" id="Address" name="Address" type="text">
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>



                <br />
                <div class="form-group">
                    <div class="col-sm-10 ">
                        <label class="control-label py-2 " for="Address">المحافظة  </label>


                    </div>
                    <div class="col-sm-10">
                        <select id="ddl_Governrate" onchange="loadCity()" class="form-control"></select>
                    </div>
                </div>
                <div class="form-group py-2">
                    <div class="col-sm-10">
                        <label class="control-label py-2 " for="Address">المدينة</label>

                    </div>
                    <div class="col-sm-10">
                        <select id="ddl_City" class="form-control"></select>
                    </div>
                </div>

                <div class="form-group py-2">
                    <div class="col-sm-10">
                        <label class="control-label py-2">الجنس</label>

                    </div>
                    <div class="col-sm-10">
                        <select id="ddl_Gender" class="form-control"></select>
                    </div>
                </div>


            
                <div class="col-sm-10 py-3">
                    <input type="submit" value="التالي" class="btn btn-primary w-100 py-2" />  @*onclick="AddMember()"*@
                </div>
            </div>


        </div>
        <div class="col-sm-2"></div>
    </div>
</div>

}


<div id="GetAllMembersDiv" class="table-responsive">


</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(document).ready(function () {

            loadGender();
            LoadGovernrate();
            loadCity();
            //GetAllMembers();
        });


          function loadGender() {
            $('#ddl_Gender option').each(function () {
                $(this).remove();
            });
            var url = "@Url.Action("LoadGender", "MEMBER")";
              var result = CreateAjaxRequest(url, "get", {});
            $("#ddl_Gender").append('<option >--Please Select--</option>');
            for (var i in result) {
                $("#ddl_Gender").append('<option value=' + result[i].ID + '>' + result[i].GenderName + '</option>');
            }

        }

        function LoadGovernrate() {
            $('#ddl_Governrate option').each(function () {
                $(this).remove();
            });
            var url = "@Url.Action("GetAllGovernrates","MEMBER")";
            var type = "GET";
            var result = CreateAjaxRequest(url, type, {});
            for (var i in result) {
                $("#ddl_Governrate").append('<option value=' + result[i].ID + '>' + result[i].GovernarteName + '</option>');
            }


        }

        function loadCity() {
            var dept_id = $("#ddl_Governrate").val();
            $('#ddl_City option').each(function () {
                $(this).remove();
            });
            var url = "@Url.Action("GetGovCities", "MEMBER")";
            var type = "POST";
            var result = CreateAjaxRequest(url, type, { governmentid: dept_id });
            $("#ddl_City").append('<option >--Please Select--</option>');
            for (var i in result) {
                $("#ddl_City").append('<option value=' + result[i].ID + '>' + result[i].CityName + '</option>');
            }
        }





            function AddMember() {

                var FullName = $("#FullName ").val();
                var PhoneNo = $("#Phone").val();
                var age = $("#txt_age").val();
                var NationalId = $("#NationalId ").val();
                var Address = $("#Address").val();
                var CityID = $("#ddl_City").val();
                var Genderid = $("#ddl_Gender").val();
         



                if (FullName == "" ||
                    PhoneNo == "" ||
                    age == "" ||
                    Address == "" ||
                    CityID == null ||
                    Genderid == null 
                   )
                    alert("Please enter all required data");
                else {
                    var url = "@Url.Action("Create","MEMBER")";
                    var result = CreateAjaxRequest(url, "post",
                        {
                            name: FullName,
                            phone: PhoneNo,
                            nationalid: NationalId,
                            Age: age,
                            address: Address,
                            IDNumber: NationalId,
                            jid: CityID,
                            GenderId: Genderid


                        });

                    @*if (result != null) {
                        window.location.href = "@Url.Action("Register","Account")";
                        ClearAllFormData();

                    }*@
                   // GetAllMembers();

                }


            }
            function GetAllMembers() {
                var url = "@Url.Action("LoadAllMembers","MEMBER")";

                $("#GetAllMembersDiv").html('');
                var result = CreateAjaxRequest(url, "get", {});

                if (result != null) {
                    if (result.length > 0) {

                        var tr = '';
                        tr += '<table class="table table-striped table-bordered table-hover dataTables-example">';
                        tr += '<thead>';
                        tr += '   <tr>';
                        tr += '       <th>Full Name</th>';
                        tr += '       <th>Gender</th>';
                        tr += '       <th> Phone Number</th>';
                        tr += '       <th>Address </th>';
                        tr += '       <th>National Id </th>';
                        tr += '       <th>Governrate </th>';
                        tr += '       <th>City </th>';

                        tr += '         <th>Edit</th>';
                        tr += '            <th>Delete</th>';
                        tr += '    </tr>';
                        tr += '</tr></thead>';
                        tr += '<tbody>';


                        for (var i = 0; i < result.length; i++) {
                            tr += '<tr>';
                            tr += '<td>' + result[i].FullName + '</td>';
                            tr += '<td>' + result[i].GenderName + '</td>';
                            tr += '<td>' + result[i].PhoneNo + '</td>';
                            tr += '<td>' + result[i].Address + '</td>';
                            tr += '<td>' + result[i].NationalId + '</td>';
                            tr += '<td>' + result[i].GovernarteName + '</td>';
                            tr += '<td>' + result[i].CityName + '</td>';
                            tr += '<td><a href="#" onclick="EditThisMember(' + result[i].ID + ');return false;"><i class="fa fa-edit" style="color:blue;font-weight:bold"></i></a></td>';
                            tr += '<td><a href="#" onclick="DeleteThisMember(' + result[i].ID + ');return false;"><i class="fa fa-trash" style="color:red;font-weight:bold;"></i></a></td>';
                            tr += '</tr>';
                        }

                        tr += '</tbody>';
                        tr += '  </table>';
                        $("#GetAllMembersDiv").append(tr);
                        $('.dataTables-example').DataTable({
                            "ordering": false
                        });
                    }
                }
            }

            function EditThisMember(mid) {

                $(window).scrollTop(0);
                loadGender();

                var url = "@Url.Action("LoadMemberForEdit","MEMBER")";

                var result = CreateAjaxRequest(url, "post", { memberid: mid });
                for (var i = 0; i < result.length; i++) {
                    $("#FullName ").val(result[i].FullName);

                    $("#ddl_Gender").val(result[i].GenderId);

                    $("#Phone").val(result[i].PhoneNo);
                    $("#NationalId ").val(result[i].NationalId);
                    $("#Address").val(result[i].Address);
                    LoadGovernrate();
                    $("#ddl_Governrate").val(result[i].governmentid);
                    loadCity();
                    $("#ddl_City").val(result[i].CityID);
                }

            }

            function DeleteThisMember(mid) {
                var x = confirm("Are you sure you want to delete this ?");
                if (x == true) {

                    var type = "POST";
                    var url = "@Url.Action("DeleteMember", "MEMBER")";

                    var result = CreateAjaxRequest(url, type, { memberid: mid });

                    alert(result);
                    GetAllMembers();
                }
            }

            function ClearAllFormData() {


                $("#FullName ").val(null);
                $("#Phone").val(null);
                $("#NationalId ").val(null);
                $("#Address").val(null);
                $("#ddl_Governrate").val(null);
                $("#ddl_City").val(null);


            }






    </script>

}