GradProjectV5/Controllers/PharmacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GradProjectV5.Models;
using Microsoft.AspNet.Identity;

namespace GradProjectV5.Controllers
{
    [Authorize]
    public class PharmacyController : Controller
    {
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }


        [HttpPost]
        public dynamic Create(Pharamacy p)
        {
            if (ModelState.IsValid)
            {
                MyProjectDBEntities db = new MyProjectDBEntities();
                var userid = User.Identity.GetUserId();
                var member = db.Members.FirstOrDefault(x => x.UserId == userid);
                Pharamacy pharamacy = new Pharamacy();
                pharamacy.IsDeleted = false;
                pharamacy.PharmacyAddress = p.PharmacyAddress;
                pharamacy.PharmacyName = p.PharmacyName;
                pharamacy.PharmacyPhone = p.PharmacyPhone;
                if (member != null)
                    pharamacy.PharmacyOwnerId = member.ID;

                db.Pharamacies.Add(pharamacy);
                db.SaveChanges();
                return RedirectToAction("Index");


            }


            return View(p);




        }

        [HttpGet]
       
        public dynamic Index()
        {
            return View();
        }

        [HttpPost]
        public dynamic GetMyPharmacies()
        {

            MyProjectDBEntities db = new MyProjectDBEntities();
            
            var userid = User.Identity.GetUserId();
            var member = db.Members.FirstOrDefault(x => x.UserId == userid && x.IsDeleted == false);
           var tmp = db.Pharamacies.Where(x => x.IsDeleted == false && 
                                               x.PharmacyOwnerId == member.ID ).Select(x =>new{
                PharmacyAddress= x.PharmacyAddress == null ?"":x.PharmacyAddress,
                PharmacyName= x.PharmacyName == null ?"":x.PharmacyName,
                PharmacyPhone= x.PharmacyPhone == null ?"":x.PharmacyPhone,
                FullName= x.PharmacyOwnerId == null ?"":x.Member.FullName,
                x.ID
            }).ToList();
            
            return Json(tmp , JsonRequestBehavior.AllowGet);
        }





        [HttpPost]
        public dynamic LoadPharmacyDetails(int Pharmacyid)
        {

            MyProjectDBEntities db = new MyProjectDBEntities();
            
            var tmp = db.Pharamacies.Where(x => x.IsDeleted == false && 
                                                x.ID == Pharmacyid).Select(x =>new{
                PharmacyAddress= x.PharmacyAddress == null ?"":x.PharmacyAddress,
                PharmacyName= x.PharmacyName == null ?"":x.PharmacyName,
                PharmacyPhone= x.PharmacyPhone == null ?"":x.PharmacyPhone,
                PharmacyOwnerName= x.PharmacyOwnerId == null ?"":x.Member.FullName,
                x.ID
            }).ToList();
            
            return Json(tmp , JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public dynamic RequestMedicine()
        {
            return View();
        }


        
        [HttpPost]
        public dynamic RequestMedicine(PharmacyMedicineRequest pmr)
        {
            if (ModelState.IsValid)
            {
                MyProjectDBEntities db = new MyProjectDBEntities();
                PharmacyMedicineRequest pharmacyMedicineRequest = new PharmacyMedicineRequest();
                pharmacyMedicineRequest.IsDeleted = false;
                pharmacyMedicineRequest.RequestedAmount = pmr.RequestedAmount;
                pharmacyMedicineRequest.MedicineId = pmr.MedicineId;
                pharmacyMedicineRequest.RequestPharamcyId = pmr.RequestPharamcyId;
                pharmacyMedicineRequest.RequestDate = DateTime.Now;
                pharmacyMedicineRequest.LatestRequestStatusId = 1;
                db.PharmacyMedicineRequests.Add(pharmacyMedicineRequest);
                db.SaveChanges();
                PhMedicineRequestStatu  requeststatus= new PhMedicineRequestStatu();
                requeststatus.PhMedicineRequestId = pharmacyMedicineRequest.ID;
                requeststatus.StatusId = 1;
                requeststatus.StatusDate = DateTime.Now;
                db.PhMedicineRequestStatus.Add(requeststatus);
                db.SaveChanges();

            }

            return View(pmr);
        }

        [HttpGet]
        public dynamic GetPhRequestedMedicine()
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            var userid = User.Identity.GetUserId();
            var member = db.Members.FirstOrDefault(x => x.UserId ==userid );
            var tmp = db.PharmacyMedicineRequests.Where(x => x.IsDeleted == false &&
                                                             x.LatestRequestStatusId != 3 &&
                                                             x.Pharamacy.PharmacyOwnerId == member.ID).Select(x => new
            {
                x.ID,
                x.RequestPharamcyId,
                x.RespondPharamacyId,
                RequestPharmacy = x.RequestPharamcyId == null ? "":x.Pharamacy.PharmacyName,
                MedicineName = x.MedicineId == null ?"":x.Medicine.MedicineName,
                RequestedAmount= x.RequestedAmount == null ?"":x.RequestedAmount,
                requestday =x.RequestDate == null ?0: x.RequestDate.Value.Day,
                requestmonth = x.RequestDate == null ?0:x.RequestDate.Value.Month,
                requestyear = x.RequestDate == null ?0:x.RequestDate.Value.Year,
                StatusName = x.LatestRequestStatusId == null ?"":x.Status.StatusName,
                RespondPharmacy =x.RespondPharamacyId == null ? "": x.Pharamacy1.PharmacyName,
                respondday =x.RespondDate == null ? 0:x.RespondDate.Value.Day,
                respondmonth = x.RespondDate == null ? 0:x.RespondDate.Value.Month,
                respondyear = x.RespondDate == null ? 0:x.RespondDate.Value.Year,
            }).ToList();
            return Json(tmp, JsonRequestBehavior.AllowGet);


        }






        [HttpGet]
        public dynamic AllPhMedicineRequests()
        {
            return View();
        }


        [HttpGet]
        public dynamic GetAllPhRequestedMedicine()
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            var tmp = db.PharmacyMedicineRequests.Where(x => x.IsDeleted == false && 
                                                             x.LatestRequestStatusId == 1 ).Select(x => new
            {
                x.ID,
                x.Pharamacy.Member.FullName,
                RequestPharmacy = x.RequestPharamcyId == null ? "":x.Pharamacy.PharmacyName,
                MedicineName = x.MedicineId == null ?"":x.Medicine.MedicineName,
                RequestedAmount= x.RequestedAmount == null ?"":x.RequestedAmount,
                requestday =x.RequestDate == null ?0: x.RequestDate.Value.Day,
                requestmonth = x.RequestDate == null ?0:x.RequestDate.Value.Month,
                requestyear = x.RequestDate == null ?0:x.RequestDate.Value.Year,
                StatusName = x.LatestRequestStatusId == null ?"":x.Status.StatusName
            }).ToList();
            return Json(tmp, JsonRequestBehavior.AllowGet);


        }

        [HttpPost]
        public dynamic DonateMedicine(int requestid , int respondpharmacyid , string amount)
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            var tmp = db.PharmacyMedicineRequests.Find(requestid);
            tmp.RespondPharamacyId = respondpharmacyid;
            tmp.RespondedAmount = amount;
            tmp.RespondDate = DateTime.Now;
            tmp.LatestRequestStatusId = 2;
            db.SaveChanges();
            PhMedicineRequestStatu phMedicineRequestStatu = new PhMedicineRequestStatu();
            phMedicineRequestStatu.PhMedicineRequestId = requestid;
            phMedicineRequestStatu.StatusId = 2;
            phMedicineRequestStatu.StatusDate = DateTime.Now;
            db.PhMedicineRequestStatus.Add(phMedicineRequestStatu);
            db.SaveChanges();
            return "تم تسجيل تبرعك بنجاح";


        }

        [HttpPost]
        public dynamic CloseMedicineRequest(int requestid)
        {
            MyProjectDBEntities db = new MyProjectDBEntities();
            var tmp = db.PharmacyMedicineRequests.Find(requestid);
            tmp.LatestRequestStatusId = 3;
            db.SaveChanges();
            PhMedicineRequestStatu phMedicineRequestStatu = new PhMedicineRequestStatu();
            phMedicineRequestStatu.PhMedicineRequestId = requestid;
            phMedicineRequestStatu.StatusId = 3;
            phMedicineRequestStatu.StatusDate = DateTime.Now;
            db.PhMedicineRequestStatus.Add(phMedicineRequestStatu);
            db.SaveChanges();
            return "تم إغلاق الطلب بنجاح";



        }
        
    }
}

GradProjectV5/Views/Pharmacy/AllPhMedicineRequests.cshtml
<div id="AllMedicineRequestDiv">

</div>


<div class="modal fade" id="DonateMedicineModal" tabindex="-1" aria-labelledby="DonateMedicineModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">نموذج تبرع بدواء متاح</h5>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <div class="col-md-4">
                        <label class="control-label py-2">إسم الصيدلية )المتبرع(</label>
                    </div>
                    <div class="col-md-6">
                        <select id="ddl_responded_pharmacy" class="form-control p-2"></select>
                    </div>
                    <div class="col-md-2">
                        <a href="@Url.Action("Create")"><i class="fa fa-plus" style="color: blue; font-weight: bold"></i></a>

                    </div>



                </div>
               
                <div class="form-group">
                    <div class="col-md-4">
                        <label class="control-label py-2">الكمية المتاحة </label>
                    </div>
                    <div class="col-md-6">
                        <input type="number" class="form-control-lg" id="txt_available_amount"/>
                    </div>
                    <div class="col-md-2">

                    </div>
                </div>

            </div>
            <div class="modal-footer">
             
                    <button type="button"onclick="DonateMedicine();" class="btn btn-primary ">حفظ</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إغلاق</button>


            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function() {
            LoadAllPhMedicineRequest();
            LoadMyPharmacies();
        });




        function LoadMyPharmacies() {
            $('#ddl_responded_pharmacy option').each(function() {
                $(this).remove();
            });
            var url = "@Url.Action("GetMyPharmacies", "Pharmacy")";
            var result = CreateAjaxRequest(url, "post", {});
            for (var i in result) {
                $("#ddl_responded_pharmacy")
                    .append('<option value=' + result[i].ID + '>' + result[i].PharmacyName + '</option>');
            }


        }


           function LoadAllPhMedicineRequest() {
            var url = "@Url.Action("GetAllPhRequestedMedicine", "Pharmacy")";

            $("#AllMedicineRequestDiv").html('');
            var tr = '';
            var result = CreateAjaxRequest(url, "get", {});

                    if (result != null && result.length > 0) {



                    tr += '<table class="table table-striped table-bordered table-hover dataTables-example">';
                    tr += '<thead>';
                    tr += '   <tr>';
                        tr += '       <th>إسم الصيدلية</th>';
                        tr += '       <th>مالك الصيدلية</th>';
                    tr += '       <th> الدواء المطلوب</th>';
                    tr += '       <th> الكمية</th>';
                    tr += '       <th>تاريخ الطلب</th>';
                        tr += '       <th>حالة الطلب</th>';
                        tr += '       <th>تبرع الأن</th>';


                    tr += '    </tr>';
                    tr += '</tr></thead>';
                    tr += '<tbody>';


                    for (var i = 0; i < result.length; i++) {
                        tr += '<tr>';
                        tr += '<td>' + result[i].RequestPharmacy + '</td>';
                        tr += '<td>' + result[i].FullName + '</td>';
                        tr += '<td>' + result[i].MedicineName + '</td>';
                        tr += '<td>' + result[i].RequestedAmount + '</td>';
                        tr += '<td>' + result[i].requestday + "/" + result[i].requestmonth+ "/" + result[i].requestyear + '</td>';
                        tr += '<td>' + result[i].StatusName + '</td>';
                        tr += '<td><button type="button" onclick="OpenDonateMedicineModal(' + result[i].ID+');" class="btn btn-primary">تبرع</button></td>';
                        tr += '</tr>';
                    }

                    tr += '</tbody>';
                    tr += '  </table>';
                    $("#GetAllMembersDiv").append(tr);
                    $('.dataTables-example').DataTable({
                        "ordering": false
                    });

            }
            $("#AllMedicineRequestDiv").append(tr);
        }


        function OpenDonateMedicineModal(id) {

                global_requestid = id;
                $('#DonateMedicineModal').modal('show');




        }


        function DonateMedicine() {
            var pharmacyid = $("#ddl_responded_pharmacy").val();
            var amountvalue = $("#txt_available_amount").val();
            if (pharmacyid == null) 
                alert("من فضلك أضف او إختار صيدلية للتبرع بإسمها");
             else if (amountvalue == "") 
                alert("من فضلك أدخل كمية للتبرع بها");
             else {
                var url = "@Url.Action("DonateMedicine","Pharmacy")";
                var result = CreateAjaxRequest(url,
                    "post",
                    {
                        requestid: global_requestid,
                        respondpharmacyid: pharmacyid,
                        amount: amountvalue
                    });
                alert(result);
                LoadAllPhMedicineRequest();
            }
        }
    </script>
}

GradProjectV5/Views/Pharmacy/Create.cshtml
@model GradProjectV5.Models.Pharamacy

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container bg-white">
    <div class="row  ">
        <p class="lead fs-2 text-center p-5 " style="font-weight:400">
            أضف صيدليتك و انضم لطبيب الخير
        </p>

    </div>
</div>
<div>
    <p class="fs-4 lead text-center text-info p-4" style="font-weight: 500">بيانات الصيدلية</p>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.PharmacyName, htmlAttributes: new { @class = "py-3 text-info lead fs-5", style = "font-weight: 400" })
                <div class="col-sm-10 ">
                    @Html.EditorFor(model => model.PharmacyName, new { htmlAttributes = new { @class = "form-control p-2" } })
                    @Html.ValidationMessageFor(model => model.PharmacyName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PharmacyAddress, htmlAttributes: new { @class = "py-3 text-info lead fs-5", style = "font-weight: 400" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.PharmacyAddress, new { htmlAttributes = new { @class = "form-control p-2" } })
                    @Html.ValidationMessageFor(model => model.PharmacyAddress, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PharmacyPhone, new { @class = "py-3 text-info lead fs-5", style = "font-weight: 400" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.PharmacyPhone, new { htmlAttributes = new { @class = "form-control p-2" } })
                    @Html.ValidationMessageFor(model => model.PharmacyPhone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group pt-4 w-100 text-center py-4 ">
                <div class="col-sm-10 ">
                    <input type="submit" value="حفظ" class="btn btn-primary w-100 py-2" />

                </div>
            </div>
        </div>

    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GradProjectV5/Views/Pharmacy/Index.cshtml
@{
    ViewBag.Title = "Index - Pharmacy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br/>

<p class="text-center text-info fs-3">تمت اضافة صيدلية بنجاح </p>
<p class="text-center fs-4">
    يمكنك إضافة صيدلية جديدة عن طريق الضغط علي 
    @Html.ActionLink("إضافة جديد", "Create","",new {@class="text-decoration-none"})
</p>


<div id="MyPharmaciesDiv">

</div>
@section scripts
{
    <script>
        $(document).ready(function() {
            GetMyPharmacies();
        });


                    function GetMyPharmacies() {
                var url = "@Url.Action("GetMyPharmacies","Pharmacy")";

                $("#MyPharmaciesDiv").html('');
                var tr = '';
                var result = CreateAjaxRequest(url, "post", {});

                if (result != null) {
                    if (result.length > 0) {

                  
                        tr += '<table class="table table-striped table-bordered table-hover dataTables-example">';
                        tr += '<thead>';
                        tr += '   <tr>';
                        tr += '       <th>إسم الصيدلية</th>';
                        tr += '       <th>إسم المالك</th>';
                        tr += '       <th> العنوان</th>';
                        tr += '       <th>رقم التليفون </th>';
                
                        tr += '    </tr>';
                        tr += '</tr></thead>';
                        tr += '<tbody>';


                        for (var i = 0; i < result.length; i++) {
                            tr += '<tr>';
                            tr += '<td>' + result[i].PharmacyName + '</td>';
                            tr += '<td>' + result[i].FullName + '</td>';
                            tr += '<td>' + result[i].PharmacyAddress + '</td>';
                            tr += '<td>' + result[i].PharmacyPhone + '</td>';
                            tr += '</tr>';
                        }

                        tr += '</tbody>';
                        tr += '  </table>';
                        tr += '<br>';
                        tr += '<p>يمكنك إضافة الدواء الفائض عن احتياجك عن طريق الضغط علي <a href="#" onclick="EditThisMember();return false;"><i class="fa fa-plus" style="color:blue;font-weight:bold"></i></a>';
                        tr += '<p>يمكنك طلب الدواء الناقص لديك عن طريق الضغط علي <a href="@Url.Action("RequestMedicine" ) "><i class="fa fa-plus" style="color:blue;font-weight:bold"></i></a>';
                        $("#GetAllMembersDiv").append(tr);
                        $('.dataTables-example').DataTable({
                            "ordering": false
                        });
                    }
                }
                $("#MyPharmaciesDiv").append(tr);
                    }


    </script>
}

GradProjectV5/Views/Pharmacy/RequestMedicine.cshtml
@model GradProjectV5.Models.PharmacyMedicineRequest





@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        <div class="col-sm-2">
            <label class="control-label py-2">اسم الصيدلية  </label>
        </div>
        <div class="col-sm-10">
            <select id="RequestPharamcyId" name="RequestPharamcyId" class="form-control p-2"></select>
        </div>
        <div class="col-sm-1">
            <a href="@Url.Action("Create")"><i class="fa fa-plus" style="color:blue;font-weight:bold"></i></a>

        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-2">
            <label class="control-label py-2">اسم الدواء </label>

        </div>
        <div class="col-sm-10">
            <select id="MedicineId" name="MedicineId" class="form-control p-2"></select>
        </div>
        <div class="col-sm-1">
            <a href="@Url.Action("Create","Medicine" )"><i class="fa fa-plus" style="color:blue;font-weight:bold"></i></a>

        </div>
    </div>



    <div class="form-group">
        <div class="col-sm-2">
            @Html.LabelFor(model => model.RequestedAmount, htmlAttributes: new { @class = "control-label py-2 " })
        </div>
        <div class="col-sm-10">
            @Html.EditorFor(model => model.RequestedAmount, new { htmlAttributes = new { @class = "form-control p-2" } })
            @Html.ValidationMessageFor(model => model.RequestedAmount, "", new { @class = "text-danger" })
        </div>
        <div class="col-sm-1"></div>

    </div>











    <div class="form-group pt-4 w-100 text-center py-4 ">
        <div class="col-sm-10 ">
            <input type="submit" value="حفظ" class="btn btn-primary w-100 py-2" />

        </div>
    </div>
   

    <br/> <br/>
    <div id="PharmacyRequestMedicineDiv"></div>

}

<div class="modal fade" id="PharmacyDetailsModal" tabindex="-1" aria-labelledby="OpenDonateMedicineModalModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            </div>
            <div class="modal-body" id="PharmacyDetailsModalBody">
              


            </div>
         

        </div>
        <div class="modal-footer">
            

        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(document).ready(function() {
            LoadMyPharmacies();
            LoadMedicine();
            LoadPhMedicineRequest();
        });


        function LoadMyPharmacies() {
            $('#RequestPharamcyId option').each(function() {
                $(this).remove();
            });
            var url = "@Url.Action("GetMyPharmacies", "Pharmacy")";
            var result = CreateAjaxRequest(url, "post", {});
            for (var i in result) {
                $("#RequestPharamcyId")
                    .append('<option value=' + result[i].ID + '>' + result[i].PharmacyName + '</option>');
            }


        }

        function LoadMedicine() {
            $('#MedicineId option').each(function() {
                $(this).remove();
            });
            var url = "@Url.Action("Index", "Medicine")";
            var result = CreateAjaxRequest(url, "get", {});
            for (var i in result) {
                $("#MedicineId").append('<option value=' + result[i].ID + '>' + result[i].MedicineName + '</option>');
            }


        }

        function LoadPhMedicineRequest() {
            var url = "@Url.Action("GetPhRequestedMedicine", "Pharmacy")";

            $("#PharmacyRequestMedicineDiv").html('');
            var tr = '';
            var result = CreateAjaxRequest(url, "get", {});

            if (result != null) {
                if (result.length > 0) {


                    tr += '<table class="table table-striped table-bordered table-hover dataTables-example">';
                    tr += '<thead>';
                    tr += '   <tr>';
                    tr += '       <th>إسم الصيدلية</th>';
                    tr += '       <th> الدواء المطلوب</th>';
                    tr += '       <th> الكمية</th>';
                    tr += '       <th>تاريخ الطلب</th>';
                    tr += '       <th>حالة الطلب</th>';
                    tr += '       <th>الجهة التي ردت علي الطلب</th>';
                    tr += '       <th>تاريخ الرد</th>';
                    tr += '       <th>إنهاء الطلب</th>';

                    tr += '    </tr>';
                    tr += '</tr></thead>';
                    tr += '<tbody>';


                    for (var i = 0; i < result.length; i++) {
                        tr += '<tr>';
                        tr += '<td><a href="#" onclick="GetPharmacyDetails(' + result[i].RequestPharamcyId + ');return false;">' + result[i].RequestPharmacy + '</a></td>';

                        tr += '<td>' + result[i].MedicineName + '</td>';
                        tr += '<td>' + result[i].RequestedAmount + '</td>';
                        tr += '<td>' + result[i].requestday + "/" + result[i].requestmonth+ "/" + result[i].requestyear + '</td>';
                        tr += '<td>' + result[i].StatusName + '</td>';
                        tr += '<td><a href="#" onclick="GetPharmacyDetails(' + result[i].RespondPharamacyId + ');return false;">' + result[i].RespondPharmacy + '</a></td>';
                        if (result[i].respondyear == 0) {
                            tr += '<td></td>';
                        } else {
                            tr += '<td>' + result[i].respondday + "/" + result[i].respondmonth + "/" + result[i].respondyear + '</td>';

                        }

                        tr += '<td><button type="button"onclick="CloseMedicineRequest(' + result[i].ID+');" class="btn btn-primary ">إغلاق</button></td>';

                        tr += '</tr>';
                    }

                    tr += '</tbody>';
                    tr += '  </table>';
                    tr += '<br>';
                    tr +=
                        '<p>يمكنك إضافة الدواء الفائض عن احتياجك عن طريق الضغط علي <a href="#" onclick="EditThisPharmacy();return false;"><i class="fa fa-plus" style="color:blue;font-weight:bold"></i></a>';
                    tr +=
                        '<p>يمكنك طلب الدواء الناقص لديك عن طريق الضغط علي <a href="@Url.Action("RequestMedicine") "><i class="fa fa-plus" style="color:blue;font-weight:bold"></i></a>';
                    $("#GetAllPharmacysDiv").append(tr);
                    $('.dataTables-example').DataTable({
                        "ordering": false
                    });
                }
            }
            $("#PharmacyRequestMedicineDiv").append(tr);
        }




        function GetPharmacyDetails(ID) {
            $("#PharmacyDetailsModalBody").html("");
            var url = "@Url.Action("LoadPharmacyDetails","Pharmacy")";
            var result = CreateAjaxRequest(url, "post", { Pharmacyid: ID });
            var tr = '';
            tr += '<table style="width:100%" class="table table-bordered  table-striped  "> ';
            tr += '<tbody>';
            for (var i in result) {

                tr += '<tr >';
                tr += ' <td>إسم الصيدلية</td>';
                tr += ' <td  >' + result[i].PharmacyName + '</td>';
                tr += '</tr>';
                tr += '<tr >';
                tr += ' <td>إسم المالك</td>';
                tr += ' <td  >' + result[i].PharmacyOwnerName + '</td>';
                tr += '</tr>';
                tr += '<tr >';
                tr += ' <td>رقم التليفون</td>';
                tr += ' <td  >' + result[i].PharmacyPhone + '</td>';
                tr += '</tr>';
                tr += '<tr >';
                tr += ' <td>العنوان</td>';
                tr += ' <td  >' + result[i].PharmacyAddress + '</td>';
                tr += '</tr>';
             
           
          
         
           
            





      

            }

            tr += '</tbody>';
            tr += '  </table>';
            $("#PharmacyDetailsModalBody").append(tr);
            $("#PharmacyDetailsModal").modal('show');

        }



        function CloseMedicineRequest(id) {
            var x = confirm("هل انت متأكد من تنفيذ هذا الإجراء");
            if (x == true) {
                var url = "@Url.Action("CloseMedicineRequest","Pharmacy")";
                var result = CreateAjaxRequest(url,
                    "post",
                    {
                        requestid: id
                    });
                alert(result);
                LoadPhMedicineRequest();
            }
        }
    </script>
}